### PR TITLE
New ic_launcher

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Hi,

i created a new ic_launcher-icon based on the [server app icon](https://github.com/nerzhul/ocsms/blob/master/img/app.svg).

It is similar to [ownCloud Notes](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes) and ownCloud News-icon.

What do you think?

ic_launcher
web_hi_res_512
ic_launcher-web

### CODE REVIEW

**Comment by nerzhul** [comment]
Build failed

**Comment by stefan-niedermann** [comment]
Crazy. Have a look at the [jenkins-output](https://jenkins.unix-experience.fr/job/ownCloud%20SMS%20%28Android%29%20-%20PR/37/console).

> Cannot run program "ant" (in directory "/usr/local/jenkins/jobs/ownCloud SMS (Android) - PR/workspace"): error=2, No such file or directory

I have really no idea - look at the commit: I just replaced 4 .png-files and added a .svg-file at the root.
I did no code-changes.

**Comment by nerzhul** [comment]
@stefan-niedermann don't look at jenkins atm i need to fix some builds on my Android builder for a few libre projects... Seems interesting icon, but confusing a little bit with mails no ? This is a great job, but if you have idea to make your icon more sms friendly than mail friendly don't hesitate, else i will merge it in 1 week

**Comment by stefan-niedermann** [comment]
Err - no problem. i just thought the android client app should have the same icon as the server app.
Isn't this the correspondenting server app? https://github.com/nerzhul/ocsms/blob/master/img/app.svg

**Comment by nerzhul** [comment]
You are right :) then i merge, thank you :)

**Comment by nerzhul** [comment]
Will fix the build later, because my jenkins builder uses ant and we use gradle since a long time now :(

**Comment by nerzhul** [comment]
Thanks for your contribution

**Comment by stefan-niedermann** [comment]
What do you think about a more proper icon like this? Its a well-known sms icon since the android-default app is nearly the same. i would create a svg for the server app and an icon in the blue style for the android client if you want.
ocsms

**Comment by nerzhul** [comment]
I like it ! Agree for server & client

**Comment by stefan-niedermann** [comment]
ic_launcher

Pull-Request will follow...

**Comment by nerzhul** [comment]
Very good  job ! I'm working on material design for the app, will follow this color scheme

**Comment by stefan-niedermann** [comment]
Thanks, you can have a look at my [styles.xml](https://github.com/stefan-niedermann/OwnCloud-Notes/blob/master/app/src/main/res/values/styles.xml) and my [colors.xml](https://github.com/stefan-niedermann/OwnCloud-Notes/blob/master/app/src/main/res/values/colors.xml) if this helps.

Would be cool if the whole eco system of ownCloud apps and android-companigons would have a similar look & feel :)

**Pull request merged**
