### PR TITLE
Create sv_google_playstore_strings.xml

### PR DESCRIPTION
**Pull request by enoch85**

### CODE REVIEW

**Comment by enoch85** [comment]
@nerzhul  You mean like this?

**Comment by nerzhul** [comment]
no res/values-sv/[file].xml :)

**Comment by enoch85** [comment]
@nerzhul How do i create res/values-sv ?

**Comment by nerzhul** [comment]
do you know git ?

**Comment by enoch85** [comment]
No. :/

**Comment by nerzhul** [comment]
you may look at a tutorial to do this translation it could be better :(

**Comment by enoch85** [comment]
Put it on Transifex instead. Much easier! :)

**Comment by nerzhul** [comment]
I will look at this a day :p i don't know how to integrate it properly with github, maybe i try this this weekend

**Pull request closed without merging**
