### PR TITLE
Add zh-rCN translation

### PR DESCRIPTION
**Pull request by liweitianux**
Add new zh-rCN translation.

I never did Android app development, so I'm not sure whether these two new files is enough for the Chinese (Simplified) support.

### CODE REVIEW

**Comment by nerzhul** [comment]
hi @liweitianux , thanks for your contribution. I will look at the correct values name for zh-rCN translation to be sure it's good and then merge your PR.

**Comment by nerzhul** [comment]
Hi @liweitianux i forget this issue, can you rebase today or tomorrow ? If you cant i will merge it manualy but we will loose trace of your PR in commit log

**Comment by liweitianux** [comment]
Hi @nerzhul , I just rebased my branch to the latest master, and also added some minor updates.   I think it's ready to be merged.  Thanks.

**Comment by nerzhul** [comment]
Merged thanks for your work !

**Pull request merged**
