### PR TITLE
Fix launcher icon

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Hi @nerzhul,

unfortunately I can't get the app to compile in my current setup but found a mistake I made formerly when I did the UI theming stuff for your app, that is the launcher icon. While I created all assets in the mipmap folders where they should be I forgot to remove the one in the drawable folder and also link to the mipmap version in the AndroidManifest.

This PR fixes this issue but I couldn't test it, so it is a blind PR. I am sorry for that. If you find the time to give it a try you should see a crisp launcher icon instead of an slightly blurry one which is to to the drawable image which gets resized...

Sorry for any trouble due to me not able to run the app.. :(

### CODE REVIEW

**Comment by nerzhul** [comment]
hello,
what is your android version ? i don't have a such issue and no customer report that on playstore

**Comment by AndyScherzinger** [comment]
My Android version is 7.1.1 but that doesn't matter since it is not related to the Android version but eagle eyes...

This is the issue to be fixed by this PR:
screenshot_20171004-234336

If you look closely at the Nextcloud SMS icon you can see that it is blurred while e.g. the Passman icon is crispy. This PR should fix this.

**Comment by AndyScherzinger** [comment]
You can click the image to get it at full resolution. This isn't a bug but rather a papercut issue design wise

**Comment by nerzhul** [comment]
merged thanks

**Comment by AndyScherzinger** [comment]
Glad you like it :) Always a pleasure to contribute!

**Pull request merged**
