### PR TITLE
Translation too long, and get's cut off

### PR DESCRIPTION
**Pull request by enoch85**
A possible solution for cut off text. But, would be better to fix in the code somehow.

Right now it only shows "Appinformation och" not the whole text. @nerzhul

### CODE REVIEW

**Comment by nerzhul** [comment]
Thanks

**Comment by enoch85** [comment]
Is it possible to dynamically set the width of the left menu so that long text fits?

**Comment by nerzhul** [comment]
@enoch85 i don't think it's possible, but i can verify, you match parent, not childs

**Comment by enoch85** [comment]
>  you match parent, not childs

Please explain, I don't get it. :)

**Comment by nerzhul** [comment]
in android when you set width and height you set values depending on parent size (match_parent) or static size if i remember, this component is a little bit complicated

**Comment by enoch85** [comment]
Aah, ok. Maybe the guys over at https://github.com/nextcloud/android can help. What do you say @AndyScherzinger @tobiasKaminsky?

**Comment by AndyScherzinger** [comment]
Material design more or less specifies the size. So if the text doesn't fit we ellipsize it in the Nextcloud app and that would be standard behavior. So the best solution is to choose texts for the menu that fit the design :/

**Pull request merged**
