### PR TITLE
Swedish Translation

### PR DESCRIPTION
**Pull request by enoch85**
Translation into Swedish of the ownCloud SMS app.

### CODE REVIEW

**Comment by enoch85** [comment]
@nerzhul Please review.

**Comment by nerzhul** [comment]
It's a bit better, don't forget to translate errors :)

**Comment by nerzhul** [comment]
And also, look at the build, you have some XML errors

**Comment by enoch85** [comment]
@nerzhul The second langue in Sweden is English, and best practice is to don't translate error messages as it's easier to google them if they appear.

XML errors? I'm not a dev, maybe you can help?

**Comment by nerzhul** [comment]
on the build, click on details you arrives on my jenkins, then go to the console:
http://jenkins.unix-experience.fr/job/ownCloud%20SMS%20%28Android%29%20-%20PR/23/console
Look at the bottom you will have the xml error and line

**Comment by enoch85** [comment]
How do I change it, and what should the value be instead?

Isn't it easier if you merge this and fix the XML error afterwards?

**Comment by nerzhul** [comment]
i can do this but this is not good to break the build because of a commit

**Comment by enoch85** [comment]
So what should I do?

**Comment by enoch85** [comment]
Or will you do it?

**Comment by nerzhul** [comment]
i'll look at it

**Comment by enoch85** [comment]
Thanks!

**Comment by nerzhul** [comment]
Commited with changes, thanks

**Comment by enoch85** [comment]
Thanks!

**Pull request closed without merging**
