### PR TITLE
Move to Nextcloud

### LINKED ISSUE #116: Move to Nextcloud
Since all major apps (mail, contacts, notes, news) moved to Nextcloud: Do you have any plans to move to Nextcloud as primary platform?
If yes: I would be able to provide a pull request with new theme-colors and icons if you wish.

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Fix #116

- [x] Adjust strings and translations
- [x] Change theme color
- [x] Adjust icon color

### CODE REVIEW

**Comment by nerzhul** [comment]
Thanks for your work, i think we should rename owncloud SMS to NextCloud Phone Sync as suggested by @enoch85

**Comment by stefan-niedermann** [comment]
Are you sure? What is synced but the sms? One could be confused and think this app should sync contacts, files, calendars, apps and so one if it is just called "phone sync"?

**Comment by nerzhul** [comment]
@stefan-niedermann yes atm it's SMS, it's not easy to change this name and it can be confusing, but i get some ideas like syncing calls, notify cloud instance when calls events occurs in real time, send GPS positions (permitting some apps to use it for showing maps and do more things...)

**Comment by nerzhul** [comment]
Maybe it's not a good idea for android app, but for server backend, which can easily split functions

**Comment by stefan-niedermann** [comment]
Hm, well if you are planning to sync calls, GPS and so on, the icon will be outdated...
I created a new sample of what the icon could look like in the future:

bildschirmfoto vom 2016-12-15 10 31 10

But this and the rebrand should imho wait until the new features are coming.
Let's merge this for now (if you are fine with it) and when the new features are implemented @ping me and i will 

---

Just for the future: Here is the source code of the possible new icon above:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   enable-background="new 0 0 595.275 311.111"
   xml:space="preserve"
   height="512"
   width="512"
   version="1.1"
   y="0px"
   x="0px"
   id="svg2"
   viewBox="0 0 512 512"
   inkscape:version="0.48.5 r10040"
   sodipodi:docname="ic_launcher.svg"><metadata
     id="metadata10"><rdf:RDF><cc:Work
         rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" /></cc:Work></rdf:RDF></metadata><defs
     id="defs8" /><sodipodi:namedview
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1"
     objecttolerance="10"
     gridtolerance="10"
     guidetolerance="10"
     inkscape:pageopacity="0"
     inkscape:pageshadow="2"
     inkscape:window-width="1366"
     inkscape:window-height="688"
     id="namedview6"
     showgrid="false"
     inkscape:zoom="0.73698733"
     inkscape:cx="192.03236"
     inkscape:cy="275.27119"
     inkscape:window-x="0"
     inkscape:window-y="27"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg2" /><rect
     rx="70"
     ry="70"
     height="448"
     width="448"
     y="32"
     x="32"
     id="rect4"
     style="fill:#0082C9" /><path
     inkscape:connector-curvature="0"
     d="M 248.5,346 H 113.50001 V 136 H 248.5 m -41.78573,255.00001 h -51.42856 v -15 h 51.42856 M 232.42858,91 H 129.57142 A 38.571428,45 0 0 0 91,136 V 376.00001 A 38.571428,45 0 0 0 129.57142,421 H 232.42858 A 38.571428,45 0 0 0 271,376.00001 V 136 A 38.571428,45 0 0 0 232.42858,91 z"
     id="path4539"
     style="fill:#ffffff" /><path
     inkscape:connector-curvature="0"
     d="m 362.5,310.54546 a 54.375,54.545456 0 0 1 -54.375,-54.54547 c 0,-9.0909 2.26563,-17.90909 6.34375,-25.45455 L 301.2375,217.27272 C 294.16875,228.45454 290,241.72726 290,255.99999 a 72.499999,72.727273 0 0 0 72.5,72.72728 V 356 l 36.25,-36.36364 -36.25,-36.36364 m 0,-99.99999 V 156 L 326.25001,192.36363 362.5,228.72727 v -27.27274 a 54.375,54.545456 0 0 1 54.375,54.54546 c 0,9.09091 -2.26563,17.9091 -6.34375,25.45454 l 13.23125,13.27274 C 430.83125,283.54545 435,270.27272 435,255.99999 a 72.499999,72.727273 0 0 0 -72.5,-72.72726 z"
     id="path4631"
     style="fill:#ffffff" /></svg>
```
Logo based on [Material Design Icons](https://materialdesignicons.com/)

**Comment by nerzhul** [comment]
Very nice work, i think this could do the trick ! Maybe we should link this issue with server issue to have more feedbacks

**Comment by jancborchardt** [comment]
@stefan-niedermann great icon! :)

**Comment by stefan-niedermann** [comment]
Thanks, like i said i will provide a PR as soon as the new name and target of this app is chosen :)

**Pull request merged**
