### PR TITLE
Fix gradle build, remove unused library

### PR DESCRIPTION
**Pull request by est31**
Fix gradle build (and build using jitpack), and also remove unused library.

### CODE REVIEW

**Comment by nerzhul** [comment]
Build failed

**Comment by est31** [comment]
Fixes #98.

**Comment by est31** [comment]
This will make building more easier, you only need to do `gradle assemble` in order to create an apk, no copying of `nrz-androidlib` needed, gradle gets a copy itself.

**Comment by est31** [comment]
Also required for clean F-droid build.

**Comment by nerzhul** [comment]
I'm fixing the jenkins build, which is outdated and uses ant

**Comment by nerzhul** [comment]
@est31 i dropped nrzandroid lib, can you resolve your PR and squash ?

**Comment by est31** [comment]
Updated

**Comment by nerzhul** [comment]
Build failed

**Comment by nerzhul** [comment]
I merge it, will do more test to upstream google play store version before next release

**Comment by nerzhul** [comment]
Thanks @est31

**Comment by kilbith** [comment]
Where is the 2nd approval ??

**Pull request merged**
